[tool.poetry]
name = "finalproject-Shilenko-Nikolay-M25-555"
version = "1.0.0"
description = "Консольное приложение для управления валютным кошельком"
authors = ["Nikolai Shilenko <nick.shilenko@gmail.com>"]
readme = "README.md"
packages = [{include = "finalproject_Shilenko_Nikolay_M25-555"}]

[tool.poetry.dependencies]
python = "^3.8"
prettytable = "^3.10.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.2"

[tool.poetry.scripts]
project = "finalproject_Shilenko_Nikolay_M25-555.main:main"

[tool.ruff]
line-length = 120
target-version = "py38"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B"]
ignore = []

[tool.ruff.format]
quote-style = "double"
